#!/usr/bin/env python3
"""
Converts the store-landmark spreadsheet into config/store-landmarks.json.

The service reads JSON, not xlsx: no spreadsheet parser in the runtime, the file
diffs readably in git, and it ships inside the serverless bundle. Re-run this
whenever the sheet changes.

    python3 scripts/import-store-landmarks.py ~/Downloads/store_landmarks_mapped1.xlsx
"""
import json, sys, pathlib
import openpyxl

src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'store_landmarks_mapped1.xlsx').expanduser()
out = pathlib.Path('config/store-landmarks.json')

wb = openpyxl.load_workbook(src, read_only=True, data_only=True)
ws = wb['Stores']
rows = list(ws.iter_rows(values_only=True))
header = [str(h).strip() if h else '' for h in rows[0]]

def col(name):
    return header.index(name)

idx = {k: col(k) for k in
       ['Store ID', 'Store_name', 'Pincode', 'Latitude', 'Longitude',
        'Business Address', 'Landmark Detail', 'Map URL']}

def clean(v):
    if v is None: return None
    s = str(v).strip()
    return s or None

stores, skipped = {}, []
for r in rows[1:]:
    sid = clean(r[idx['Store ID']])
    if not sid:
        skipped.append(r)
        continue
    stores[sid.upper()] = {
        'storeId': sid,
        'storeName': clean(r[idx['Store_name']]),
        'pincode': clean(r[idx['Pincode']]),
        'latitude': clean(r[idx['Latitude']]),
        'longitude': clean(r[idx['Longitude']]),
        'businessAddress': clean(r[idx['Business Address']]),
        'landmarkDetail': clean(r[idx['Landmark Detail']]),
        'mapUrl': clean(r[idx['Map URL']]),
    }

payload = {
    'meta': {
        'source': src.name,
        'storeCount': len(stores),
        'note': 'Generated by scripts/import-store-landmarks.py. Keyed by upper-cased Store ID, '
                'which is what the store-locator API returns as storeId.',
    },
    'stores': stores,
}
out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + '\n')
print(f'{len(stores)} stores -> {out}')
if skipped:
    print(f'  skipped {len(skipped)} rows with no Store ID')
withLandmark = sum(1 for s in stores.values() if s['landmarkDetail'])
print(f'  with a landmark detail: {withLandmark}/{len(stores)}')
